FROM openjdk:11-jre-slim

EXPOSE 8080

COPY ./build/libs/*.jar app.jar

ARG JDBC_URL
ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD

ENV JDBC_URL ${JDBC_URL}
ENV DATABASE_USERNAME ${DATABASE_USERNAME}
ENV DATABASE_PASSWORD ${DATABASE_PASSWORD}

ENTRYPOINT ["java","-jar","/app.jar"]