FROM openjdk:11-jre-slim

EXPOSE 8080

COPY ./build/libs/*.jar app.jar

ARG PROFILE
ARG CLOUD_CONFIG_USERNAME
ARG CLOUD_CONFIG_PASSWORD

ENV PROFILE ${PROFILE}
ENV CLOUD_CONFIG_USERNAME ${CLOUD_CONFIG_USERNAME}
ENV CLOUD_CONFIG_PASSWORD ${CLOUD_CONFIG_PASSWORD}

ENTRYPOINT ["java","-jar","/app.jar"]
