name: CD

on:
  push:
    branches:
      - main
      - "hotfix/**"
      - "feature/**"
      - "release/**"

jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11 ]
    outputs:
      version: ${{ steps.get_version.outputs.BRANCH_NAME }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'zulu'

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            build
            --no-daemon
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Get branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr /# -)" >> $GITHUB_ENV

      - name: Build and push to Github Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/team-xquare/v1-service-dms:latest
            ghcr.io/team-xquare/v1-service-dms:${{ env.BRANCH_NAME }}